title: Raviraj Halarnekar
email: ravirajrh@outlook.com
description: Network Engineer
url: "https://ravirajh.github.io"
baseurl: "/sshravi"
twitter_username: ravirajrh
github_username: ravirajrh

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

# URL Structure Setting
permalink: /cheatsheet/:title/
