title: Raviraj Halarnekar
email: ravirajrh@outlook.com
description: Network Engineer & System Admin
baseurl: ""
url: ""
twitter_username: ravirajrh
github_username: ravirajrh

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag